services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://server:5000
      - NEXT_PUBLIC_WS_BASE_URL=ws://server:5000
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/typing-master
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
