services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - typing-master-db
    environment:
      MONGO_URI: "mongodb://typing-master-db:27017/typing-master"
      JWT_SECRET: "blahblahblah"
      JWT_SECRET_EXPIRY: 172800000
      COOLING_PERIOD_WS: 5000
      COOLING_PERIOD_HTTP: 10000
      BEGINNER_GAME_TIMER: 30000
      EASY_GAME_TIMER: 20000
      EXPERT_GAME_TIMER: 15000
      LEGEND_GAME_TIMER: 10000

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network

  typing-master-db:
    image: mongo:6.0
    container_name: typing-master-mongo
    ports:
      - "27017:27017"
    volumes:
      - typing-mongo-data:/data/db
    networks:
      - app-network

volumes:
  typing-mongo-data:

networks:
  app-network:
    driver: bridge
